# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='报表名称')),
                ('report_type', models.CharField(choices=[('asset', '资产报表'), ('alarm', '告警报表'), ('performance', '性能报表'), ('compliance', '合规报表'), ('custom', '自定义报表')], max_length=16, verbose_name='报表类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('config', models.JSONField(default=dict, verbose_name='报表配置')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='定时生成')),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=64, verbose_name='Cron 表达式')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='pdf', max_length=8, verbose_name='输出格式')),
                ('notify_email', models.TextField(blank=True, default='', verbose_name='接收邮箱')),
                ('created_by', models.CharField(max_length=64, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'rpt_template',
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='报表标题')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='generating', max_length=16, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, default='', max_length=512, verbose_name='文件路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小 (bytes)')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('generated_by', models.CharField(max_length=64, verbose_name='生成人')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='report.reporttemplate', verbose_name='报表模板')),
            ],
            options={
                'verbose_name': '报表实例',
                'verbose_name_plural': '报表实例',
                'db_table': 'rpt_instance',
                'ordering': ['-generated_at'],
            },
        ),
    ]
