# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('template_content', models.TextField(verbose_name='模板内容 (Jinja2)')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量定义')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_templates', to='cmdb.devicetype', verbose_name='设备类型')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.manufacturer', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '配置模板',
                'verbose_name_plural': '配置模板',
                'db_table': 'cm_config_template',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('rule_type', models.CharField(choices=[('regex', '正则匹配'), ('keyword', '关键字检查'), ('script', '脚本检查'), ('absence', '缺失检查')], max_length=16, verbose_name='规则类型')),
                ('rule_content', models.TextField(verbose_name='规则内容')),
                ('expected_result', models.JSONField(blank=True, default=dict, verbose_name='期望结果')),
                ('severity', models.CharField(default='warning', max_length=16, verbose_name='严重等级')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_rules', to='cmdb.devicetype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '合规规则',
                'verbose_name_plural': '合规规则',
                'db_table': 'cm_compliance_rule',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='是否通过')),
                ('detail', models.TextField(blank=True, default='', verbose_name='检查详情')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='cmdb.device', verbose_name='设备')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='config_management.compliancerule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '合规检查结果',
                'verbose_name_plural': '合规检查结果',
                'db_table': 'cm_compliance_result',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量值')),
                ('commands', models.TextField(blank=True, default='', verbose_name='执行命令')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('created_by', models.CharField(max_length=64, verbose_name='创建人')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('devices', models.ManyToManyField(related_name='batch_jobs', to='cmdb.Device', verbose_name='目标设备')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_management.configtemplate', verbose_name='配置模板')),
            ],
            options={
                'verbose_name': '批量任务',
                'verbose_name_plural': '批量任务',
                'db_table': 'cm_batch_job',
            },
        ),
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(default='running', max_length=16, verbose_name='配置类型')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('checksum', models.CharField(max_length=64, verbose_name='校验和 (MD5)')),
                ('backup_method', models.CharField(default='ssh', max_length=16, verbose_name='备份方式')),
                ('is_changed', models.BooleanField(default=False, verbose_name='是否有变更')),
                ('diff_content', models.TextField(blank=True, default='', verbose_name='变更差异')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_backups', to='cmdb.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '配置备份',
                'verbose_name_plural': '配置备份',
                'db_table': 'cm_config_backup',
                'ordering': ['-version'],
                'unique_together': {('device', 'version')},
            },
        ),
    ]
