# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=32, verbose_name='字典类型编码')),
                ('type_name', models.CharField(max_length=64, verbose_name='字典类型名称')),
                ('item_code', models.CharField(max_length=32, verbose_name='字典项编码')),
                ('item_name', models.CharField(max_length=64, verbose_name='字典项名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'db_table': 'sys_data_dict',
                'ordering': ['type_code', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='操作人')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('execute', '执行')], max_length=16, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=64, verbose_name='资源 ID')),
                ('resource_name', models.CharField(blank=True, default='', max_length=256, verbose_name='资源名称')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(verbose_name='操作 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User Agent')),
                ('result', models.CharField(default='success', max_length=16, verbose_name='操作结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', '基本设置'), ('notification', '通知设置'), ('collection', '采集设置'), ('alarm', '告警设置'), ('security', '安全设置')], max_length=16, verbose_name='分类')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='参数键')),
                ('value', models.TextField(verbose_name='参数值')),
                ('value_type', models.CharField(default='string', max_length=16, verbose_name='值类型')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'db_table': 'sys_parameter',
            },
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_audit_user_time'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['resource_type'], name='idx_audit_resource'),
        ),
        migrations.AlterUniqueTogether(
            name='datadict',
            unique_together={('type_code', 'item_code')},
        ),
    ]
