# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='指标名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='指标编码')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('collection_method', models.CharField(choices=[('snmp', 'SNMP'), ('ssh', 'SSH'), ('wmi', 'WMI'), ('ipmi', 'IPMI'), ('ping', 'Ping'), ('script', '自定义脚本')], max_length=16, verbose_name='采集方式')),
                ('oid', models.CharField(blank=True, default='', max_length=128, verbose_name='OID')),
                ('snmp_type', models.CharField(blank=True, default='gauge32', max_length=16, verbose_name='SNMP 数据类型')),
                ('command', models.CharField(blank=True, default='', max_length=256, verbose_name='SSH 命令')),
                ('parse_regex', models.CharField(blank=True, default='', max_length=256, verbose_name='解析正则')),
                ('script', models.TextField(blank=True, default='', verbose_name='采集脚本')),
                ('aggregation', models.CharField(choices=[('avg', '平均值'), ('max', '最大值'), ('min', '最小值'), ('sum', '求和'), ('last', '最新值')], default='avg', max_length=8, verbose_name='聚合方式')),
                ('retention_days', models.IntegerField(default=90, verbose_name='保留天数')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cmdb.devicetype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '指标定义',
                'verbose_name_plural': '指标定义',
                'db_table': 'perf_metric_definition',
            },
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='值')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_data', to='cmdb.device', verbose_name='设备')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='performance.metricdefinition', verbose_name='指标')),
            ],
            options={
                'verbose_name': '性能数据',
                'verbose_name_plural': '性能数据',
                'db_table': 'perf_metric_data',
            },
        ),
        migrations.CreateModel(
            name='InterfaceTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_octets', models.BigIntegerField(default=0, verbose_name='入方向字节')),
                ('out_octets', models.BigIntegerField(default=0, verbose_name='出方向字节')),
                ('in_bps', models.FloatField(default=0, verbose_name='入方向速率 (bps)')),
                ('out_bps', models.FloatField(default=0, verbose_name='出方向速率 (bps)')),
                ('in_utilization', models.FloatField(default=0, verbose_name='入方向利用率 (%)')),
                ('out_utilization', models.FloatField(default=0, verbose_name='出方向利用率 (%)')),
                ('in_errors', models.BigIntegerField(default=0, verbose_name='入方向错误')),
                ('out_errors', models.BigIntegerField(default=0, verbose_name='出方向错误')),
                ('in_discards', models.BigIntegerField(default=0, verbose_name='入方向丢包')),
                ('out_discards', models.BigIntegerField(default=0, verbose_name='出方向丢包')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.interface')),
            ],
            options={
                'verbose_name': '接口流量',
                'verbose_name_plural': '接口流量',
                'db_table': 'perf_interface_traffic',
            },
        ),
        migrations.CreateModel(
            name='CollectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('device_groups', models.JSONField(blank=True, default=list, verbose_name='设备分组')),
                ('interval', models.IntegerField(default=300, verbose_name='采集间隔 (秒)')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('error', '异常')], default='stopped', max_length=16, verbose_name='状态')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最后错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('devices', models.ManyToManyField(blank=True, related_name='collect_tasks', to='cmdb.Device', verbose_name='采集设备')),
                ('metrics', models.ManyToManyField(related_name='collect_tasks', to='performance.MetricDefinition', verbose_name='采集指标')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
                'db_table': 'perf_collect_task',
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', '提示'), ('minor', '次要'), ('major', '重要'), ('critical', '紧急')], max_length=16, verbose_name='阈值等级')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='下限值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='上限值')),
                ('consecutive_count', models.IntegerField(default=1, verbose_name='连续次数')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='cmdb.device', verbose_name='设备 (空=全局)')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='performance.metricdefinition', verbose_name='指标')),
            ],
            options={
                'verbose_name': '阈值配置',
                'verbose_name_plural': '阈值配置',
                'db_table': 'perf_metric_threshold',
                'unique_together': {('metric', 'device', 'level')},
            },
        ),
        migrations.AddIndex(
            model_name='metricdata',
            index=models.Index(fields=['device', 'metric', 'timestamp'], name='idx_metric_dev_time'),
        ),
        migrations.AddIndex(
            model_name='interfacetraffic',
            index=models.Index(fields=['interface', 'timestamp'], name='idx_traffic_if_time'),
        ),
    ]
