# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', '紧急'), ('major', '重要'), ('minor', '次要'), ('warning', '提示'), ('info', '信息')], max_length=16, verbose_name='严重等级')),
                ('status', models.CharField(choices=[('active', '活跃'), ('acknowledged', '已确认'), ('cleared', '已清除')], default='active', max_length=16, verbose_name='状态')),
                ('title', models.CharField(max_length=256, verbose_name='告警标题')),
                ('detail', models.TextField(blank=True, default='', verbose_name='告警详情')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('occurrence_count', models.IntegerField(default=1, verbose_name='发生次数')),
                ('is_root_cause', models.BooleanField(default=False, verbose_name='是否根因')),
                ('first_occurred_at', models.DateTimeField(verbose_name='首次发生时间')),
                ('last_occurred_at', models.DateTimeField(verbose_name='最后发生时间')),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=64, verbose_name='确认人')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('cleared_by', models.CharField(blank=True, default='', max_length=64, verbose_name='清除方式')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='清除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '实时告警',
                'verbose_name_plural': '实时告警',
                'db_table': 'alarm',
                'ordering': ['-last_occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AlarmDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='告警名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='告警编码')),
                ('severity', models.CharField(choices=[('critical', '紧急'), ('major', '重要'), ('minor', '次要'), ('warning', '提示'), ('info', '信息')], max_length=16, verbose_name='严重等级')),
                ('source', models.CharField(choices=[('trap', 'SNMP Trap'), ('syslog', 'Syslog'), ('polling', '主动轮询'), ('threshold', '阈值触发'), ('script', '脚本检测')], max_length=16, verbose_name='告警来源')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('match_rules', models.JSONField(blank=True, default=dict, verbose_name='匹配规则')),
                ('auto_clear', models.BooleanField(default=True, verbose_name='自动清除')),
                ('clear_rules', models.JSONField(blank=True, default=dict, verbose_name='清除规则')),
                ('notify_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('notify_channels', models.JSONField(blank=True, default=list, verbose_name='通知渠道')),
                ('notify_contacts', models.JSONField(blank=True, default=list, verbose_name='通知对象')),
                ('compress_window', models.IntegerField(default=300, verbose_name='压缩窗口 (秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警定义',
                'verbose_name_plural': '告警定义',
                'db_table': 'alarm_definition',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.BigIntegerField(verbose_name='原始告警 ID')),
                ('alarm_definition_code', models.CharField(blank=True, default='', max_length=64, verbose_name='告警编码')),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='设备 IP')),
                ('device_name', models.CharField(blank=True, default='', max_length=128, verbose_name='设备名称')),
                ('severity', models.CharField(max_length=16, verbose_name='严重等级')),
                ('title', models.CharField(max_length=256, verbose_name='告警标题')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('occurrence_count', models.IntegerField(default=1, verbose_name='发生次数')),
                ('first_occurred_at', models.DateTimeField(verbose_name='首次发生时间')),
                ('last_occurred_at', models.DateTimeField(verbose_name='最后发生时间')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='清除时间')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
            ],
            options={
                'verbose_name': '历史告警',
                'verbose_name_plural': '历史告警',
                'db_table': 'alarm_history',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='TrapRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('oid', models.CharField(max_length=128, verbose_name='Trap OID')),
                ('vendor', models.CharField(blank=True, default='', max_length=32, verbose_name='厂商')),
                ('severity', models.CharField(default='warning', max_length=16, verbose_name='严重等级')),
                ('title_template', models.CharField(blank=True, default='', max_length=256, verbose_name='标题模板')),
                ('detail_template', models.TextField(blank=True, default='', verbose_name='详情模板')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alarm_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.alarmdefinition', verbose_name='关联告警定义')),
            ],
            options={
                'verbose_name': 'Trap 规则',
                'verbose_name_plural': 'Trap 规则',
                'db_table': 'alarm_trap_rule',
            },
        ),
        migrations.CreateModel(
            name='SyslogRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('vendor', models.CharField(blank=True, default='', max_length=32, verbose_name='厂商')),
                ('pattern', models.TextField(verbose_name='匹配模式 (正则)')),
                ('severity_mapping', models.JSONField(blank=True, default=dict, verbose_name='等级映射')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alarm_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.alarmdefinition', verbose_name='关联告警定义')),
            ],
            options={
                'verbose_name': 'Syslog 规则',
                'verbose_name_plural': 'Syslog 规则',
                'db_table': 'alarm_syslog_rule',
            },
        ),
        migrations.CreateModel(
            name='AlarmNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32, verbose_name='通知渠道')),
                ('recipient', models.CharField(max_length=256, verbose_name='接收人')),
                ('status', models.CharField(max_length=16, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alarm.alarm', verbose_name='告警')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'alarm_notification_log',
            },
        ),
        migrations.AddIndex(
            model_name='alarmhistory',
            index=models.Index(fields=['-first_occurred_at'], name='idx_alarmhist_time'),
        ),
        migrations.AddIndex(
            model_name='alarmhistory',
            index=models.Index(fields=['device_ip'], name='idx_alarmhist_ip'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='alarm_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='alarm.alarmdefinition', verbose_name='告警定义'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='cmdb.device', verbose_name='关联设备'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='cmdb.interface', verbose_name='关联接口'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='parent_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_alarms', to='alarm.alarm', verbose_name='父告警'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status', 'severity'], name='idx_alarm_status_severity'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['device', 'status'], name='idx_alarm_device_status'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['-last_occurred_at'], name='idx_alarm_time'),
        ),
    ]
