# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='探测名称')),
                ('probe_type', models.CharField(choices=[('icmp', 'ICMP Ping'), ('tcp', 'TCP Connect'), ('dns', 'DNS Query'), ('http', 'HTTP GET')], max_length=8, verbose_name='探测类型')),
                ('target_ip', models.GenericIPAddressField(verbose_name='目标 IP')),
                ('target_port', models.IntegerField(blank=True, null=True, verbose_name='目标端口')),
                ('target_url', models.URLField(blank=True, default='', verbose_name='目标 URL')),
                ('interval', models.IntegerField(default=60, verbose_name='探测间隔 (秒)')),
                ('timeout', models.IntegerField(default=5, verbose_name='超时 (秒)')),
                ('rtt_threshold_ms', models.FloatField(default=100, verbose_name='RTT 阈值 (ms)')),
                ('loss_threshold_percent', models.FloatField(default=5, verbose_name='丢包率阈值 (%)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_probes', to='cmdb.device', verbose_name='源设备')),
            ],
            options={
                'verbose_name': 'SLA 探测',
                'verbose_name_plural': 'SLA 探测',
                'db_table': 'net_sla_probe',
            },
        ),
        migrations.CreateModel(
            name='SLAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtt_ms', models.FloatField(default=0, verbose_name='RTT (ms)')),
                ('loss_percent', models.FloatField(default=0, verbose_name='丢包率 (%)')),
                ('jitter_ms', models.FloatField(default=0, verbose_name='抖动 (ms)')),
                ('is_reachable', models.BooleanField(default=True, verbose_name='是否可达')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='探测时间')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='network.slaprobe', verbose_name='探测任务')),
            ],
            options={
                'verbose_name': 'SLA 数据',
                'verbose_name_plural': 'SLA 数据',
                'db_table': 'net_sla_data',
            },
        ),
        migrations.CreateModel(
            name='NetflowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(verbose_name='源 IP')),
                ('dest_ip', models.GenericIPAddressField(verbose_name='目的 IP')),
                ('source_port', models.IntegerField(verbose_name='源端口')),
                ('dest_port', models.IntegerField(verbose_name='目的端口')),
                ('protocol', models.IntegerField(verbose_name='协议号')),
                ('bytes_count', models.BigIntegerField(verbose_name='字节数')),
                ('packets_count', models.BigIntegerField(verbose_name='包数')),
                ('first_seen', models.DateTimeField(verbose_name='首次出现')),
                ('last_seen', models.DateTimeField(verbose_name='最后出现')),
                ('input_interface', models.IntegerField(blank=True, null=True, verbose_name='入接口索引')),
                ('output_interface', models.IntegerField(blank=True, null=True, verbose_name='出接口索引')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.device', verbose_name='采集设备')),
            ],
            options={
                'verbose_name': 'NetFlow 记录',
                'verbose_name_plural': 'NetFlow 记录',
                'db_table': 'net_netflow_record',
            },
        ),
        migrations.AddIndex(
            model_name='sladata',
            index=models.Index(fields=['probe', 'timestamp'], name='idx_sla_probe_time'),
        ),
        migrations.AddIndex(
            model_name='netflowrecord',
            index=models.Index(fields=['source_ip', 'timestamp'], name='idx_netflow_src_time'),
        ),
        migrations.AddIndex(
            model_name='netflowrecord',
            index=models.Index(fields=['dest_ip', 'timestamp'], name='idx_netflow_dst_time'),
        ),
    ]
