# Generated by Django 4.2.30 on 2026-08-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_controlleradmin_equipmenttypecmdbmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='platform_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='管控平台设备ID'),
        ),
    ]
