# Generated by Django 4.2.30 on 2026-08-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_networkequipmentmodel_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='api_timeout',
            field=models.IntegerField(default=5, verbose_name='API超时(秒)'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='cpu_utilization_rate',
            field=models.CharField(default='0', max_length=255, verbose_name='CPU使用率'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='memory_utilization_rate',
            field=models.CharField(default='0', max_length=255, verbose_name='内存使用率'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='problem_count',
            field=models.IntegerField(default=0, verbose_name='问题数'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='telnet_timeout',
            field=models.IntegerField(default=5, verbose_name='Telnet超时(秒)'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='zabbix_host_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zabbix主机ID'),
        ),
        migrations.AddField(
            model_name='networkequipmentmodel',
            name='zabbix_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zabbix状态'),
        ),
        migrations.CreateModel(
            name='NetworkSnmpInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('sys_name', models.CharField(blank=True, default='', max_length=200, verbose_name='系统名')),
                ('sys_services', models.CharField(blank=True, default='', max_length=200, verbose_name='服务')),
                ('sys_location', models.CharField(blank=True, default='', max_length=200, verbose_name='位置')),
                ('sys_contact', models.CharField(blank=True, default='', max_length=200, verbose_name='联系人')),
                ('sys_descr', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('sys_up_time', models.CharField(blank=True, default='', max_length=200, verbose_name='运行时长')),
                ('sys_object_id', models.CharField(blank=True, default='', max_length=200, verbose_name='OID')),
                ('snmp_engine_time', models.CharField(blank=True, default='', max_length=200, verbose_name='引擎时间')),
                ('app_version', models.CharField(blank=True, default='', max_length=200, verbose_name='应用版本')),
                ('hardware_version', models.CharField(blank=True, default='', max_length=200, verbose_name='硬件版本')),
                ('ss_cpu_idle', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU空闲')),
                ('monitor_way', models.CharField(blank=True, default='', max_length=200, verbose_name='监控方式')),
                ('cpu_1m', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU 1分钟')),
                ('cpu_5m', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU 5分钟')),
                ('cpu_5s', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU 5秒')),
                ('mem_total_free', models.CharField(blank=True, default='', max_length=200, verbose_name='内存空闲')),
                ('mem_total_real', models.CharField(blank=True, default='', max_length=200, verbose_name='内存总量')),
                ('sys_up_datetime', models.CharField(blank=True, default='', max_length=200, verbose_name='启动时间')),
                ('total_memory', models.CharField(blank=True, default='', max_length=200, verbose_name='总内存')),
                ('total_used', models.CharField(blank=True, default='', max_length=200, verbose_name='已用内存')),
                ('used_rate', models.CharField(blank=True, default='', max_length=200, verbose_name='使用率')),
                ('cpu_ratio', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU比率')),
                ('memory_ratio', models.CharField(blank=True, default='', max_length=200, verbose_name='内存比率')),
                ('physical_descr', models.CharField(blank=True, default='', max_length=200, verbose_name='物理描述')),
                ('physical_mfg_name', models.CharField(blank=True, default='', max_length=200, verbose_name='厂商')),
                ('physical_model_name', models.CharField(blank=True, default='', max_length=200, verbose_name='型号')),
                ('physical_name', models.CharField(blank=True, default='', max_length=200, verbose_name='物理名')),
                ('physical_serial_num', models.CharField(blank=True, default='', max_length=200, verbose_name='序列号')),
                ('physical_software_rev', models.CharField(blank=True, default='', max_length=200, verbose_name='软件版本')),
                ('sys_log', models.TextField(blank=True, default='', verbose_name='系统日志')),
                ('sys_version', models.CharField(blank=True, default='', max_length=200, verbose_name='系统版本')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_info', to='cmdb.networkequipmentmodel', verbose_name='设备')),
            ],
            options={
                'verbose_name': '网络设备系统信息',
                'verbose_name_plural': '网络设备系统信息',
                'db_table': 'esight_network_snmp_info',
            },
        ),
        migrations.CreateModel(
            name='NetworkIpInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('ip_net_to_media_if_index', models.IntegerField(blank=True, null=True, verbose_name='接口索引')),
                ('ip_net_to_media_phys_address', models.CharField(blank=True, default='', max_length=255, verbose_name='物理地址')),
                ('ip_net_to_media_net_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP地址')),
                ('ip_ad_ent_net_mask', models.CharField(blank=True, default='', max_length=100, verbose_name='子网掩码')),
                ('ip_net_to_media_type', models.CharField(blank=True, default='', max_length=255, verbose_name='类型')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_infos', to='cmdb.networkequipmentmodel', verbose_name='设备')),
            ],
            options={
                'verbose_name': '网络设备IP信息',
                'verbose_name_plural': '网络设备IP信息',
                'db_table': 'esight_network_ip_info',
            },
        ),
        migrations.CreateModel(
            name='NetworkInterfaceInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('if_index', models.IntegerField(blank=True, null=True, verbose_name='接口索引')),
                ('if_name', models.CharField(blank=True, default='', max_length=255, verbose_name='接口名')),
                ('if_descr', models.CharField(blank=True, default='', max_length=255, verbose_name='接口描述')),
                ('if_type', models.CharField(blank=True, default='', max_length=100, verbose_name='接口类型')),
                ('if_phys_address', models.CharField(blank=True, default='', max_length=100, verbose_name='物理地址')),
                ('if_admin_status', models.CharField(blank=True, default='', max_length=100, verbose_name='管理状态')),
                ('if_oper_status', models.CharField(blank=True, default='', max_length=100, verbose_name='操作状态')),
                ('if_speed', models.CharField(blank=True, default='', max_length=100, verbose_name='速率')),
                ('if_alias', models.CharField(blank=True, default='', max_length=200, verbose_name='别名')),
                ('if_in_octets', models.CharField(blank=True, default='', max_length=100, verbose_name='入流量')),
                ('if_out_octets', models.CharField(blank=True, default='', max_length=100, verbose_name='出流量')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='cmdb.networkequipmentmodel', verbose_name='设备')),
            ],
            options={
                'verbose_name': '网络设备接口信息',
                'verbose_name_plural': '网络设备接口信息',
                'db_table': 'esight_network_interface',
            },
        ),
    ]
