# Generated by Django 4.2.30 on 2026-08-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_networkequipmentmodel_api_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpSubnetManagerGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='分组名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_manager_group_parent', to='cmdb.ipsubnetmanagergroupmodel', verbose_name='父分组')),
            ],
            options={
                'verbose_name': 'IP管理分组',
                'verbose_name_plural': 'IP管理分组',
                'db_table': 'esight_ip_subnet_manager_group',
            },
        ),
        migrations.CreateModel(
            name='IpSubnetManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='子网名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('subnet_addr', models.CharField(max_length=150, verbose_name='子网地址')),
                ('subnet_mask', models.CharField(max_length=150, verbose_name='子网掩码')),
                ('timeout', models.IntegerField(default=300, verbose_name='超时时间')),
                ('add_type', models.CharField(default='', max_length=50, verbose_name='添加方式')),
                ('vlan_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='VLAN名称')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='位置')),
                ('scan_status', models.CharField(default='not_scan', max_length=50, verbose_name='扫描状态')),
                ('scan_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='扫描信息')),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('last_scan_start_timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('last_scan_start_str', models.CharField(blank=True, max_length=50, null=True)),
                ('last_scan_end_timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('last_scan_end_str', models.CharField(blank=True, max_length=50, null=True)),
                ('elapsed', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('ip_used_count', models.IntegerField(default=0, verbose_name='已用数量')),
                ('ip_available_count', models.IntegerField(default=0, verbose_name='可用数量')),
                ('ip_transient_count', models.IntegerField(default=0, verbose_name='瞬态数量')),
                ('ip_not_scanned_count', models.IntegerField(default=0, verbose_name='未扫描')),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_ip_subnet', to='cmdb.controlleradmin', verbose_name='控制器')),
                ('ip_manager_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_group_manager', to='cmdb.ipsubnetmanagergroupmodel', verbose_name='IP管理分组')),
            ],
            options={
                'verbose_name': 'IP子网',
                'verbose_name_plural': 'IP子网',
                'db_table': 'esight_ip_subnet_manager',
            },
        ),
        migrations.CreateModel(
            name='IpManagerScanLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('request_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='request_id')),
                ('subnet_addr', models.CharField(max_length=50, verbose_name='子网地址')),
                ('initial_data', models.TextField(blank=True, null=True, verbose_name='原始扫描结果')),
                ('scan_type', models.CharField(default='ip', max_length=50, verbose_name='扫描类型')),
                ('scan_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='扫描信息')),
                ('ip_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_manager_scan_log', to='cmdb.ipsubnetmanagermodel', verbose_name='IP管理')),
            ],
            options={
                'verbose_name': 'IP扫描日志',
                'verbose_name_plural': 'IP扫描日志',
                'db_table': 'esight_ip_manager_scan_log',
            },
        ),
        migrations.CreateModel(
            name='IpAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('ip_address', models.CharField(max_length=150, verbose_name='IP地址')),
                ('host_name', models.TextField(default='', verbose_name='主机名')),
                ('ip_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='IP地址类型')),
                ('mac_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='MAC地址')),
                ('mac_addr_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC地址类型')),
                ('vendor', models.CharField(blank=True, max_length=150, null=True, verbose_name='供应商')),
                ('state', models.CharField(default='unknown', max_length=50, verbose_name='状态')),
                ('state_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='原因')),
                ('state_reason_ttl', models.CharField(blank=True, max_length=50, null=True, verbose_name='state_reason_ttl')),
                ('ip_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_manager_address', to='cmdb.ipsubnetmanagermodel', verbose_name='IP管理')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'db_table': 'esight_ip_address',
            },
        ),
    ]
