# Generated by Django 4.2.30 on 2026-08-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_ipsubnetmanagergroupmodel_controlleradmin_exec_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlleradmin',
            name='exec_mode',
            field=models.CharField(blank=True, choices=[('', '远程代理(agent)'), ('agent', '远程代理(agent)'), ('local', '本地直连(local)')], default='', max_length=20, verbose_name='执行模式'),
        ),
        migrations.CreateModel(
            name='WafAttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(db_index=True, verbose_name='日志时间')),
                ('dev_ip', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='设备IP')),
                ('dev_id', models.CharField(blank=True, default='', max_length=64, verbose_name='设备HASH')),
                ('src_ip', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='源IP')),
                ('src_port', models.CharField(blank=True, default='', max_length=16, verbose_name='源端口')),
                ('dst_ip', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='目的IP')),
                ('dst_port', models.CharField(blank=True, default='', max_length=16, verbose_name='目的端口')),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='攻击类型')),
                ('event_type_id', models.IntegerField(default=0, verbose_name='攻击类型ID')),
                ('severity', models.CharField(blank=True, default='', max_length=32, verbose_name='危险等级')),
                ('severity_id', models.IntegerField(default=0, verbose_name='危险等级ID')),
                ('action', models.CharField(blank=True, default='', max_length=32, verbose_name='处置动作')),
                ('action_id', models.IntegerField(default=0, verbose_name='动作ID')),
                ('msg', models.TextField(blank=True, default='', verbose_name='事件描述')),
                ('rule_id', models.CharField(blank=True, default='', max_length=64, verbose_name='规则ID')),
                ('proto', models.CharField(blank=True, default='', max_length=32, verbose_name='协议')),
                ('method', models.CharField(blank=True, default='', max_length=16, verbose_name='HTTP方法')),
                ('domain', models.CharField(blank=True, default='', max_length=255, verbose_name='域名')),
                ('uri', models.TextField(blank=True, default='', verbose_name='URL')),
                ('raw', models.TextField(blank=True, default='', verbose_name='原始日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': 'WAF攻击日志',
                'verbose_name_plural': 'WAF攻击日志',
                'db_table': 'cmdb_waf_attack_log',
                'ordering': ['-log_time'],
                'indexes': [models.Index(fields=['log_time', 'src_ip'], name='cmdb_waf_at_log_tim_046ac6_idx'), models.Index(fields=['dev_ip', 'log_time'], name='cmdb_waf_at_dev_ip_04de43_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('boot_task_type', models.CharField(default='1', max_length=50, verbose_name='启动配置执行类型')),
                ('boot_start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动开始时间')),
                ('boot_end_time', models.DateTimeField(blank=True, null=True, verbose_name='启动结束时间')),
                ('boot_config_script', models.TextField(blank=True, default='', verbose_name='启动配置脚本')),
                ('boot_config_content', models.TextField(blank=True, default='', verbose_name='启动配置内容')),
                ('boot_username', models.CharField(blank=True, default='', max_length=512, verbose_name='启动配置执行人')),
                ('run_task_type', models.CharField(default='1', max_length=50, verbose_name='运行配置执行类型')),
                ('run_start_time', models.DateTimeField(blank=True, null=True, verbose_name='运行开始时间')),
                ('run_end_time', models.DateTimeField(blank=True, null=True, verbose_name='运行结束时间')),
                ('running_config_script', models.TextField(blank=True, default='', verbose_name='运行配置脚本')),
                ('running_config_content', models.TextField(blank=True, default='', verbose_name='运行配置内容')),
                ('run_username', models.CharField(blank=True, default='', max_length=512, verbose_name='运行配置执行人')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_config', to='cmdb.networkequipmentmodel', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备配置',
                'verbose_name_plural': '设备配置',
                'db_table': 'esight_network_config',
            },
        ),
    ]
