# Generated by Django 4.2.30 on 2026-08-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_waf_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='VscanWebTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(db_index=True, unique=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, verbose_name='任务名称')),
                ('scan_time', models.DateTimeField(blank=True, null=True, verbose_name='扫描时间')),
                ('site_total', models.IntegerField(default=0, verbose_name='网站数')),
                ('vuln_total', models.IntegerField(default=0, verbose_name='漏洞总数(原始)')),
                ('high_total', models.IntegerField(default=0, verbose_name='高危数(等级0)')),
                ('dedup_total', models.IntegerField(default=0, verbose_name='去重漏洞数')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': 'WEB扫描任务',
                'verbose_name_plural': 'WEB扫描任务',
                'db_table': 'cmdb_vscan_web_task',
                'ordering': ['-taskid'],
            },
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='alert_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='告警信息'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, default='WAF', max_length=32, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='policy_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='策略名称'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='protocol_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='协议类型'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='站点名称'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='src_country',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='源国家'),
        ),
        migrations.CreateModel(
            name='VscanWebVuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, verbose_name='任务名称')),
                ('severity', models.IntegerField(db_index=True, default=0, verbose_name='风险等级')),
                ('name', models.CharField(db_index=True, max_length=512, verbose_name='漏洞名称')),
                ('url', models.CharField(blank=True, default='', max_length=1024, verbose_name='漏洞URL')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='分类')),
                ('param', models.TextField(blank=True, default='', verbose_name='问题参数')),
                ('comment', models.TextField(blank=True, default='', verbose_name='备注')),
                ('testcase', models.TextField(blank=True, default='', verbose_name='测试用例')),
                ('pluginid', models.IntegerField(db_index=True, default=0, verbose_name='ruleid')),
                ('scan_time', models.DateTimeField(blank=True, null=True, verbose_name='扫描时间')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': 'WEB漏洞',
                'verbose_name_plural': 'WEB漏洞',
                'db_table': 'cmdb_vscan_web_vuln',
                'ordering': ['taskid', 'severity', 'name'],
                'indexes': [models.Index(fields=['taskid', 'severity'], name='cmdb_vscan__taskid_3a1e02_idx')],
                'unique_together': {('taskid', 'severity', 'name', 'url')},
            },
        ),
        migrations.CreateModel(
            name='VscanWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, verbose_name='任务名称')),
                ('url', models.CharField(db_index=True, max_length=1024, verbose_name='网站URL')),
                ('jobid', models.CharField(blank=True, default='', max_length=64, verbose_name='jobid')),
                ('scan_time', models.DateTimeField(blank=True, null=True, verbose_name='扫描时间')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': 'WEB扫描网站',
                'verbose_name_plural': 'WEB扫描网站',
                'db_table': 'cmdb_vscan_web_site',
                'ordering': ['-taskid'],
                'unique_together': {('taskid', 'url')},
            },
        ),
    ]
