# Generated by Django 4.2.30 on 2026-08-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_vscanwebtask_wafattacklog_alert_info_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wafattacklog',
            index=models.Index(fields=['device_type', 'log_time'], name='cmdb_waf_at_device__63d262_idx'),
        ),
    ]
