# Generated by Django 4.2.30 on 2026-08-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_add_device_type_log_time_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VscanVuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group', models.CharField(blank=True, default='', max_length=255, verbose_name='资产组')),
                ('asset_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='资产名称')),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='IP')),
                ('admin', models.CharField(blank=True, default='', max_length=255, verbose_name='管理员')),
                ('os', models.CharField(blank=True, default='', max_length=255, verbose_name='操作系统')),
                ('severity', models.IntegerField(db_index=True, default=0, verbose_name='风险等级')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='漏洞名称')),
                ('port', models.CharField(blank=True, default='', max_length=32, verbose_name='端口')),
                ('time', models.CharField(blank=True, default='', max_length=64, verbose_name='发现时间')),
                ('rid', models.CharField(blank=True, default='', max_length=64, verbose_name='漏洞ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情(JSON)')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': '系统漏洞',
                'verbose_name_plural': '系统漏洞',
                'db_table': 'cmdb_vscan_vuln',
                'ordering': ['severity', 'name'],
                'indexes': [models.Index(fields=['severity'], name='cmdb_vscan__severit_2173e0_idx'), models.Index(fields=['ip'], name='cmdb_vscan__ip_602222_idx')],
            },
        ),
    ]
