# Generated by Django 4.2.30 on 2026-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_vscanvuln'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('window_start', models.DateTimeField(blank=True, null=True, verbose_name='窗口起点')),
                ('window_minutes', models.IntegerField(default=60, verbose_name='时间窗')),
                ('severity_threshold', models.CharField(default='high', max_length=16, verbose_name='阈值')),
                ('waf_new', models.IntegerField(default=0, verbose_name='WAF新增高危')),
                ('fw_new', models.IntegerField(default=0, verbose_name='防火墙新增高危')),
                ('vuln_high', models.IntegerField(default=0, verbose_name='系统漏洞高危(现状)')),
                ('web_high', models.IntegerField(default=0, verbose_name='WEB漏洞高危(现状)')),
                ('total_new', models.IntegerField(default=0, verbose_name='攻击新增合计')),
                ('triggered', models.BooleanField(default=False, verbose_name='是否触发通知')),
                ('channels', models.CharField(blank=True, default='', max_length=64, verbose_name='通知通道')),
                ('detail', models.TextField(blank=True, default='', verbose_name='明细(JSON)')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'cmdb_alert_record',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_threshold', models.CharField(choices=[('low', '低及以上'), ('medium', '中及以上'), ('high', '高及以上')], default='high', max_length=16, verbose_name='严重级别阈值')),
                ('window_minutes', models.IntegerField(default=60, verbose_name='检测时间窗(分钟)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用告警')),
                ('dingtalk_enabled', models.BooleanField(default=False, verbose_name='钉钉推送')),
                ('dingtalk_webhook', models.CharField(blank=True, default='', max_length=512, verbose_name='钉钉Webhook')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='邮件推送')),
                ('email_to', models.CharField(blank=True, default='', max_length=512, verbose_name='邮件接收人')),
                ('email_subject_prefix', models.CharField(default='[eSight安全告警]', max_length=64, verbose_name='邮件主题前缀')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'cmdb_alert_rule',
            },
        ),
    ]
