# Generated by Django 4.2.30 on 2026-08-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_alertrecord_alertrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrecord',
            name='triggered',
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='events_new',
            field=models.IntegerField(default=0, verbose_name='新增事件'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='events_recurred',
            field=models.IntegerField(default=0, verbose_name='复现事件'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='events_resolved',
            field=models.IntegerField(default=0, verbose_name='恢复事件'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='events_suppressed',
            field=models.IntegerField(default=0, verbose_name='冷却抑制'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='是否推送'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='trigger',
            field=models.CharField(default='manual', help_text='manual=手动 / scheduled=定时', max_length=16, verbose_name='触发方式'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='cooldown_minutes',
            field=models.IntegerField(default=60, help_text='同一 fingerprint 在冷却期内不重复推送，但持续累计次数', verbose_name='同事件冷却期(分钟)'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='include_unknown_severity',
            field=models.BooleanField(default=False, help_text='WAF/FW 存在空 severity 记录，开启后按 unknown 纳入统计', verbose_name='纳入未知级别(空severity)'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notify_on_resolve',
            field=models.BooleanField(default=True, verbose_name='恢复时推送通知'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='resolve_after_minutes',
            field=models.IntegerField(default=120, help_text='事件超过该时长未再出现则判定为已恢复', verbose_name='恢复判定时间(分钟)'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='scan_interval_minutes',
            field=models.IntegerField(default=60, help_text='Celery beat 调度周期；0 表示仅手动', verbose_name='定时扫描周期(分钟)'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='事件指纹')),
                ('source', models.CharField(choices=[('WAF', 'WAF'), ('Firewall', '防火墙')], default='WAF', max_length=16, verbose_name='来源')),
                ('event_type', models.CharField(blank=True, default='', max_length=255, verbose_name='攻击类型')),
                ('src_ip', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='源IP')),
                ('dst_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='目的IP')),
                ('severity', models.CharField(blank=True, default='', max_length=32, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('firing', '触发中'), ('acked', '已确认'), ('resolved', '已恢复'), ('suppressed', '已忽略')], db_index=True, default='firing', max_length=16, verbose_name='状态')),
                ('occurrence', models.IntegerField(default=1, verbose_name='累计次数')),
                ('notify_count', models.IntegerField(default=0, verbose_name='已推送次数')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='首次出现')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后出现')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='上次推送')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('acked_by', models.CharField(blank=True, default='', max_length=64, verbose_name='确认人')),
                ('ack_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'cmdb_alert_event',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='cmdb_alert__status_509d8f_idx')],
            },
        ),
    ]
