# Generated by Django 4.2.30 on 2026-09-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_remove_alertrecord_triggered_alertrecord_events_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('day', '日报'), ('week', '周报'), ('month', '月报')], db_index=True, max_length=8, verbose_name='报类型')),
                ('period_key', models.CharField(db_index=True, help_text='day=2026-09-03 / week=2026-W36 / month=2026-09', max_length=32, verbose_name='周期键')),
                ('period_start', models.DateTimeField(verbose_name='周期开始')),
                ('period_end', models.DateTimeField(verbose_name='周期结束')),
                ('title', models.CharField(default='', max_length=128, verbose_name='标题')),
                ('data', models.TextField(default='{}', verbose_name='聚合数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '安全报表',
                'verbose_name_plural': '安全报表',
                'db_table': 'cmdb_security_report',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_key')},
            },
        ),
    ]
