# Generated by Django 3.2.25 on 2026-07-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='拓扑名称')),
                ('map_type', models.CharField(choices=[('physical', '物理拓扑'), ('logical', '逻辑拓扑'), ('vlan', 'VLAN 拓扑'), ('custom', '自定义拓扑')], max_length=16, verbose_name='拓扑类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('layout_config', models.JSONField(blank=True, default=dict, verbose_name='布局配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认拓扑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '拓扑图',
                'verbose_name_plural': '拓扑图',
                'db_table': 'topo_map',
            },
        ),
        migrations.CreateModel(
            name='TopologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称')),
                ('x', models.FloatField(default=0, verbose_name='X 坐标')),
                ('y', models.FloatField(default=0, verbose_name='Y 坐标')),
                ('layer', models.CharField(blank=True, default='', max_length=32, verbose_name='层级')),
                ('icon', models.CharField(blank=True, default='', max_length=128, verbose_name='图标')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='样式')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_nodes', to='cmdb.device', verbose_name='设备')),
                ('topology_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='topology.topologymap', verbose_name='拓扑图')),
            ],
            options={
                'verbose_name': '拓扑节点',
                'verbose_name_plural': '拓扑节点',
                'db_table': 'topo_node',
            },
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(default='physical', max_length=16, verbose_name='连接类型')),
                ('bandwidth', models.BigIntegerField(default=0, verbose_name='带宽 (bps)')),
                ('utilization', models.FloatField(default=0, verbose_name='利用率 (%)')),
                ('status', models.CharField(default='up', max_length=16, verbose_name='状态')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='样式')),
                ('source_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topo_src_links', to='cmdb.interface', verbose_name='源接口')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='topology.topologynode', verbose_name='源节点')),
                ('target_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topo_tgt_links', to='cmdb.interface', verbose_name='目标接口')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='topology.topologynode', verbose_name='目标节点')),
                ('topology_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='topology.topologymap', verbose_name='拓扑图')),
            ],
            options={
                'verbose_name': '拓扑连接',
                'verbose_name_plural': '拓扑连接',
                'db_table': 'topo_link',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('ip_ranges', models.JSONField(default=list, verbose_name='IP 范围')),
                ('protocols', models.JSONField(default=list, verbose_name='发现协议')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='发现结果')),
                ('discovered_count', models.IntegerField(default=0, verbose_name='发现设备数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credentials', models.ManyToManyField(blank=True, related_name='discovery_tasks', to='cmdb.Credential', verbose_name='尝试凭据')),
            ],
            options={
                'verbose_name': '发现任务',
                'verbose_name_plural': '发现任务',
                'db_table': 'topo_discovery_task',
            },
        ),
    ]
